config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :contacts
  get '/about' => 'pages#about'
  root'pages#home'

  

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
    
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
      
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  attr_accessor :stripe_card_token

  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end

    def create
        @contact = Contact.new(contact_params)
        
        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]

            #ContactMailer.contact_email(name, email, body).deliver
            
            flash[:success] = 'Message sent homie....'
            redirect_to new_contact_path #, notice: "Successful :)"
        else
            flash[:danger] = 'What you trying to do bruh? What kind of funny business you got going on?'
            redirect_to new_contact_path #, notice: "What you trying to do bruh???"
        end   
    end
    
    private
        def contact_params
            params.require(:contact).permit(:name, :email, :comments)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @basic_plan = Plan.find(1)
        @pro_plan = Plan.find(2)
    end
    
    def about
    end
    
    def contact
    end
    
    def mychops
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    before_action :only_current_user

    def new
       # Form for each user to fill out their own profile.
       @user = User.find( params[:user_id] )
       #@profile = @user.build_profile  Causes the user to have to create a new Profile everytime...
       @profile = Profile.new
    end
    
    def create
       @user = User.find( params[:user_id] )
       @profile = @user.build_profile(profile_params)
        if @profile.save
            flash[:success] = "Profile Updated!"
           redirect_to user_path( params[:user_id] )
        else
            render action: :new
        end
    end

    def edit
        @user = User.find( params[:user_id] )
        @profile = @user.profile
    end
    
    def update
       @user = User.find( params[:user_id] )
       @profile = @user.profile
        if @profile.update_attributes(profile_params)
            flash[:success] = "Profile Updated!"
            redirect_to user_path( params[:user_id] )
        else
            render action: :edit
        end
    end

    private
        def profile_params
            params.require(:profile).permit(:first_name, :last_name, :avatar, :subject_area, :phone_number, :contact_email, :description)
        end
        
        def only_current_user
            @user = User.find( params[:user_id] )
            redirect_to(root_url) unless @user == current_user
        end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :select_plan, only: :new
  
  
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
  end
  
  private
    def select_plan
      unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
      flash[:notice] = "Please select a membership plan to sign up."
      redirect_to root_url
      end
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @users = User.all
    end
    
    def show
       @user = User.find( params[:id] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    def subject_area_title_icon
        if @user.profile.subject_area == "Math"
            "<i class='fa fa-calculator'></i>".html_safe
        elsif @user.profile.subject_area == "Science"
            "<i class='fa fa-flask'></i>".html_safe
        elsif @user.profile.subject_area == "Engineering"
            "<i class='fa fa-gears'></i>".html_safe
        elsif @user.profile.subject_area == "Technology"
            "<i class='fa fa-code'></i>".html_safe
        elsif @user.profile.subject_area == "STREAM"
            "<i class='fa fa-graduation-cap'></i>".html_safe
        end
    end
end

app/views/contacts/new.html.erb
<div class="row">
     <div class="col-md-4 col-md-offset-4">
            <h1 class="text-center">Contact Us</h1>
            <p class="lead"><strong>LabCHOPs</strong> is “The Next Chapter in eLearning”.</p>
        <div class="well">
             <%= form_for @contact do |f| %>
            
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.text_field :email, class: 'form-control' %>
                </div>
                
                <div class="form-group">
                    <%= f.label :comments %>
                    <%= f.text_field :comments, class: 'form-control' %>
                </div>
                <%= f.submit 'Submit', class: 'btn btn-primary' %>
                
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LabCHOPS SaaS</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_include_tag "https://js.stripe.com/v3/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application' %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="navbar-wrapper">
      <!--<div class="container"> -->

        <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
		            <span class="icon-bar"></span>                
		          </button>
              <%= link_to root_path, class: 'navbar-brand' do %>
                <i class="fa fa-flask"></i>
                LabCHOPS
              <% end %>
            </div>
    
            <div id="navbar" class="navbar-collapse collapse">
              <div class="nav navbar-nav navbar-right">
                <% if current_user %>
                  <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
                <% else %>
                  <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>
                  <!-- <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success navbar-btn', method: :get %> -->
                <% end %>
              </div>
              <ul class="nav navbar-nav">
                <li><%= link_to "About", about_path %></li>
                <!-- <li> link_to "MyCHOPS", mychops_path %></li>  -->
                <li><%= link_to "Contact Us", new_contact_path %></li>
		            </li>
              </ul>
            </div>
          </div>
        </nav>

      <!-- </div> -->
</div>

<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
  
  <%= yield %>

</div>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>
</html>

app/views/pages/about.html.erb
<div class="container">
    <header>
        <h4><strong>LabCHOPs</strong> is &ldquo;The Next Chapter in eLearning&rdquo;.</h4>
    </header> 
        <div class="container">
            <div class="row">
            <div class="col-md-6 portfolio-item">
                <h2>About</h2>
                    <p><strong>LabCHOPs</strong> is an innovative web platform that will enhance the way math and science is currently being studied in schools, homes and in groups around the world. LabCHOPs is a website that is focused on building open communities for solving math and science problems and enable distributed groups to visualize complex solutions wrapped in a social networking platform.</p>
            </div>
            
            <div class="col-md-6 portfolio-item">
                <article>
                    <h2>History</h2>
                    <p><strong>LabCHOPs</strong> was initially targeted to the higher education institutes, high schools, college students and educational companies. First, the goal is to reach the local (state) educational systems; more specifically the students, local area schools, then move across the country and internationally from there. LabCHOPs is a free education based social environment for the users. We encourage colleges, universities and educational companies to integrate the application into their specific student/teacher or interactive platforms used for student assignments so teachers and professors can upload homework and assignments and be able to track students&rsquo; progress.</p>
                </article>
            </div>
        </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron text-center">

    <h1>Welcome to LabCHOPS</h1>
    <h3><!--Thank you for joining us at the Lab.--> Collaborate, study and work on various subjects over the internet from anywhere with anyone.</h3>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6 portfolio-item">
            <header><h2>Welcome</h2></header>
            <footer><p class="post-info">Thank you for joining us in the LAB...</p></footer>
            <table class="table table-striped">
                    <ul class="list-group">
					  <li class="list-group-item">Create an account</li>
					  <li class="list-group-item">Find a study partner that you know or don’t know</li>
					  <li class="list-group-item">Write you homework or notes as they are in the text box</li>
					  <li class="list-group-item">Get real-time feedback.</li>
					  <li class="list-group-item">Save and print notes to your own LabCHOPs</li>
					  <li class="list-group-item">Come back to your notes to study or share with others.</li>
					  <li class="list-group-item">Submit the work to teachers for your homework.</li>
		    </ul>
		    </table>
		    
		    <div class="bottom-sidebar">
		        <article>
		            <h2>News</h2>  
		            <footer><p class="post-info">Stayed tuned for the latest LabNEWs</p></footer>
                        <p>This site is strictly a tool to help you get help with your assignments. All users have full access to all site functions. If you would like to be a paid tutor, register here. For all other users, the objective here is to help. So please verify all assistance you receive on this site with your teacher or professor. This site provides an online place to join study groups who may be in a different part of town, etc. If your parents or siblings can’t help, there are friends and family who can. So join a group. </p> <br>
                    <ul>
    		          <li>Teachers can signup to get class notes and assignment posted and tracked</li>
    		          <li>Tutors can join to help students who do not know individuals that can help. Tutors will be tested and monitored.</li>
    		        </ul>
                </article>
		    </div>
        </div>
        
        <div class="col-md-6 portfolio-item">
            <% if user_signed_in? %>
                <% if current_user.profile %>
                    <!-- = link_to "Edit Profile", edit_user_profile_path(current_user) %> / = link_to "View Profile", user_path(current_user) %> -->
                <% else %>
                    <p>Create your profile to contribute to the community.</p>
                    <%= link_to "Create your profile", new_user_profile_path(current_user) %>
                <% end %>
            <% else %>
                <h2>Sign Up</h2>
                <div class="row">
                    <div class="col-md-6 col-md-4">
                        <h4>Basic Membership</h4> 
                        <%= link_to "Sign up Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary' %>
                        <footer><p class="post-info">Sign up for free and get basic access to the community.</p></footer>
                    </div>
                    <div class="col-md-6 col-md-4">
                        <h4>Pro Membership</h4>  
                        <%= link_to "Sign up Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success' %>
                        <footer><p class="post-info">Sign up for pro account for $9.99/month and get access to the community, contact information and online tutors!</p></footer>
                    </div>
                </div>
            <% end %>
            
            <div class="bottom-sidebar">

                <h2>Events</h2>
                <a class="twitter-timeline"  href="https://twitter.com/labchops/likes" data-widget-id="443528100295352320">Tweets by @Labchops</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            </div>
        </div>
    </div>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, html: { multipart: true } do |f|  %>
    <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :avatar %>
        <%= f.file_field :avatar, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :subject_area %>
        <%= f.select :subject_area, ['Math', 'Science', 'Engineering', 'Technology','STREAM'], {}, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :contact_email %>
        <%= f.text_field :contact_email, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.submit "Update Profile", class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Edit Your Profile</h1>
        <p class="text-center">Become a contributor to the LabCHOPs Community and fill out your profile.</p>
        <div class="well">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Create Your Profile</h1>
        <p class="text-center">Become a contributor to the LabCHOPs Community and fill out your profile.</p>
        <div class="well">
            <%= form_for @profile, url: user_profile_path do |f|  %>
                <div class="form-group">
                    <%= f.label :first_name %>
                    <%= f.text_field :first_name, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :last_name %>
                    <%= f.text_field :last_name, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :subject_area %>
                    <%= f.select :subject_area, ['Math', 'Science', 'Engineering', 'Technology','STREAM'], {}, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :phone_number %>
                    <%= f.text_field :phone_number, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :contact_email %>
                    <%= f.text_field :contact_email, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.label :description %>
                    <%= f.text_area :description, class: 'form-control' %>
                </div>
                <div class="form-group">
                    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1 class="text-center">The Lab</h1>
        <p class="lead">Welcome to the LabCHOPs community.  Users must fill out your profile to be visible.</p>
        <ul class="list-unstyled">
            <%= @users.each do |user| %>
                <% if user.profile %>
                <li>
                    <div class="well row <%= cycle('white-bg','') %>">
                        <div class="col-sm-4 text-center">
                        <% if user.profile.avatar %>
                            <%= link_to user do %>
                            <%= image_tag user.profile.avatar.url(:thumb), class: 'user-index-avatar' %> 
                            <% end %>
                        <% end %>
                        </div>
                    
                        <div>
                        <%= link_to user do %>
                        <h2><%= user.profile.first_name %>  <%= user.profile.last_name %></h2>
                        <% end %>
                        <p>
                            <%= user.profile.subject_area %>
                            <% if user.plan_id == 2 %>
                                <span class="label label-danger">PRO</span>
                            <% end %>
                        </p>
                        </div>
                    </div>
                    
                </li>
                <% end %>
                
            <% end %>
        </ul>
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-3 text-center">
        <%= image_tag @user.profile.avatar.url(:medium) %>
        <h3><%= @user.profile.first_name %> <%= @user.profile.last_name %></h3>

        <% if current_user.plan_id == 2 %>
            <div class="well profile-block contact-info">
                <h3>Contact Info</h3>
                <%= @user.profile.phone_number %></br>
                <%= @user.profile.contact_email %></br>
            </div>
        <% end %>
        <%= link_to "Edit Profile", edit_user_profile_path(current_user) %></br> 
        <%= link_to "Visit the LabCHOPs community", users_path %>
    </div>
        <div class="col-md-6">
            <h3><span class="subject-area-title-icon"><%= subject_area_title_icon %></span> <%= @user.profile.subject_area %></h3>
            <div class="well profile-block profile-description">
              <h3>Bio</h3>
              <%= @user.profile.description %></br>              
            </div>                
                <div class="well">
                    <%= render 'message' %>
                </div>
        </div>
</div>